import { v4 as uuidv4 } from "uuid"

export const state = () => ({
  projects: [
    {
      id: uuidv4(),
      title: "CNAM",
      slug: "cnam-app",
      logo: "cnam.svg",
      image: "cover.jpg",
      types: ["ALL", "APP"],
      tags: ["ALL", "UI", "UX", "DEV"],
      date: "2022-2023",
    },
    {
      id: uuidv4(),
      title: "ATS Studios",
      slug: "ats-motion",
      logo: "ats.svg",
      image: "1.jpg",
      types: ["ALL", "MOTION"],
      tags: ["ALL", "UI"],
      date: "2022",
    },
    {
      id: uuidv4(),
      title: "ATS Studios",
      slug: "ats-app",
      logo: "ats.svg",
      image: "commandes-infos.jpg",
      types: ["ALL", "APP"],
      tags: ["ALL", "UI", "UX", "DEV"],
      date: "2022",
    },
    {
      id: uuidv4(),
      title: "NGTV Expérience",
      slug: "ngtv-app",
      logo: "ngtv.svg",
      image: "login.jpg",
      types: ["ALL", "APP"],
      tags: ["ALL", "UI", "UX"],
      date: "2021-2022",
    },
    {
      id: uuidv4(),
      title: "NGTV Expérience",
      slug: "ngtv-console",
      logo: "ngtv.svg",
      image: "home.jpg",
      types: ["ALL", "APP"],
      tags: ["ALL", "UI", "UX", "DEV"],
      date: "2021-2022",
    },
    {
      id: uuidv4(),
      title: "NGTV Expérience",
      slug: "ngtv-touchapp",
      logo: "ngtv.svg",
      image: "slider.jpg",
      types: ["ALL", "APP"],
      tags: ["ALL", "UI", "UX", "DEV"],
      date: "2021-2022",
    },
    {
      id: uuidv4(),
      title: "NGTV Expérience",
      slug: "ngtv-web",
      logo: "ngtv.svg",
      image: "sportcenters.jpg",
      types: ["ALL", "WEB"],
      tags: ["ALL", "UI", "UX", "DEV"],
      date: "2021",
    },
    {
      id: uuidv4(),
      title: "Wattsense",
      slug: "wattsense-web",
      logo: "wattsense.svg",
      image: "home-illustration.jpg",
      types: ["ALL", "WEB", "MOTION"],
      tags: ["ALL", "UI", "UX", "DEV"],
      date: "2021",
    },
    {
      id: uuidv4(),
      title: "Wattsense",
      slug: "wattsense-console",
      logo: "wattsense.svg",
      image: "home.jpg",
      types: ["ALL", "APP"],
      tags: ["ALL", "UI", "UX", "DEV"],
      date: "2021",
    },
    {
      id: uuidv4(),
      title: "Continental",
      slug: "continental-print",
      logo: "continental.svg",
      image: "cover.jpg",
      types: ["ALL", "PRINT"],
      tags: ["ALL", "COMMUNICATION"],
      date: "2018-2020",
    },
  ],
});

export const getters = {
  getProjectById: (state) => (id) => {
    return state.projects.find((project) => project.slug == id)
  }
}
